### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [NanBarcenas/Trabajo-final-BioinfRepro-2017-2#1]
OK

Recuerda que al citar un repo de Dryad debes poner el repo y el artículo.

**Comment by NanBarcenas** [comment]
ok

**Comment by AliciaMstt** [comment]
No hiciste las correciones que te pedimos, siguen sin aparecer el repo  y el artículo. Corrígelo y cierra esta issue.

**Comment by AliciaMstt** [comment]
Nunca cerraste el issue... lo tendré que hacer yo :(
